### ISSUE TITLE
WHATWG list notation « » is unfamiliar to some readers

### ISSUE THREAD

**Issue by martinthomson** [jeremyroman/http-no-vary-search#4]
The draft includes this text in an example:

>  « "é 気" »

That's two layers of quoting.  One layer is probably enough.

**Comment by jeremyroman** [comment]
This isn't actually two layers of quoting, though it may be an artifact of WHATWG convention (namely, the [list literal shorthand](https://infra.spec.whatwg.org/#lists)), i.e., the variance has exactly one vary param, which is the string "é 気".

If this notation is unfamiliar to readers of IETF documents, it could be called out more explicitly in _Conventions and Definitions_ (which does link to the WHATWG infra document) or changed to some other notation.

**Comment by martinthomson** [comment]
That's a list?  Wow, that wasn't obvious.  I've seen `[]` or `()` used in other contexts with considerable success.

**Comment by jeremyroman** [comment]
Migrated to https://github.com/httpwg/http-extensions/issues/2907.
