### ISSUE TITLE
Is the default equivalent to an empty field?

### ISSUE THREAD

**Issue by martinthomson** [jeremyroman/http-no-vary-search#7]
The definition for the default says:

>  The default URL search variance is a URL search variance whose no-vary params is an empty list, vary params is wildcard, and vary on key order is true.

This is something that can be explicitly specified.  Indeed, the processing returns the default if the field is specified but empty.

But specifying the field indicates an understanding of the advanced matching algorithm, which might imply that the caller wishes to engage the algorithm.  That would mean that `https://example.com/?q&&&&` is equivalent to `https://example.com/?q&&`, where it wouldn't be otherwise.

Is it useful to distinguish an expression that engages the algorithm vs. one that does not?  Yes, the answer could be "we fall back to default processing, which is safe", but it seems like that's a logic error and somewhat surprising.

**Comment by jeremyroman** [comment]
/cc @domenic @liviutinta

> This is something that can be explicitly specified. Indeed, the processing returns the default if the field is specified but empty.

Yes, it can be explicitly specified. I'm not sure whether all HTTP implementations would permit an empty field ([RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) disavows them for the most part afaict), but values such as `key-order=?0` or `params=()` would do the trick.

> But specifying the field indicates an understanding of the advanced matching algorithm, which might imply that the caller wishes to engage the algorithm. That would mean that https://example.com/?q&&&& is equivalent to https://example.com/?q&&, where it wouldn't be otherwise.

As currently written, there is no way of getting _just_ the decoding-related behavior (like spurious ampersands and the `+` vs `%20` distinction), though you could get close by varying only on a nonsense parameter (`No-Vary-Search: params=("__iamneverspecifiedintherealworld")`). If anyone wanted this, we could add a way of expressing it (and suppressing this revert-to-default logic), such as `No-Vary-Search: encoding-only`.

> Is it useful to distinguish an expression that engages the algorithm vs. one that does not? Yes, the answer could be "we fall back to default processing, which is safe", but it seems like that's a logic error and somewhat surprising.

I'm not sure what it means to be a logic error here. My current thinking is that the value of such cases is unclear but there is risk of confusion arising from an empty and absent header having different meanings (or a facially meaningless value having a different meaning from an absent one).

It seems to me that an accidental cache miss is much better than an accidental cache hit (as you note, it's safe), so if we're going to have a single such behavior, the current, exact matching logic is the better fallback even if it compromises conceptual purity a little.

**Comment by jeremyroman** [comment]
I'm tentatively closing this as resolved, but feel free to reopen at httpwg/http-extensions (where this has moved) if you disagree.
